name: ec2ssm
on:
  push:
    tags:
      - '*' # run only against tags
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21 # https://github.com/actions/go-versions/blob/main/versions-manifest.json
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
